version: "2.1"

services:

  nginx:
    image: nginx:latest
    volumes:
      - ./html:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    tty: true
    ports:
      - 80:80
    links:
      - db
      - php
    networks:
      - default
    depends_on:
      db:
        condition: service_healthy

  php:
    image: php:7.0-fpm
    volumes:
      - ./html/:/var/www/html/
    tty: true
    expose:
      - 9000
    links:
      - db
    networks:
      - default
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mariadb:latest
    volumes:
      - db-local:/var/lib/mysql
    expose:
      - "5432"
    ports:
      - "5432:5432"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_PASSWORD: $DATABASE_ROOT_PASSWORD
      MYSQL_DATABASE: $DATABASE_NAME
      MYSQL_USER: $DATABASE_USER
      MYSQL_PASSWORD: $DATABASE_PASSWORD
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 3s
      timeout: 1s
      retries: 5
    networks:
      - default

  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - 8080:80
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: db
      PMA_USER: $DATABASE_USER
      PMA_PASSWORD: $DATABASE_PASSWORD
    depends_on:
      db:
        condition: service_healthy



### Storage Volumes Setup ###########################################

volumes:
  db-local:
    driver: "local"